/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NucleusButton {
        "buttontype": 'default' | 'dark' | 'light';
    }
    interface NucleusTwComponent {
    }
}
declare global {
    interface HTMLNucleusButtonElement extends Components.NucleusButton, HTMLStencilElement {
    }
    var HTMLNucleusButtonElement: {
        prototype: HTMLNucleusButtonElement;
        new (): HTMLNucleusButtonElement;
    };
    interface HTMLNucleusTwComponentElement extends Components.NucleusTwComponent, HTMLStencilElement {
    }
    var HTMLNucleusTwComponentElement: {
        prototype: HTMLNucleusTwComponentElement;
        new (): HTMLNucleusTwComponentElement;
    };
    interface HTMLElementTagNameMap {
        "nucleus-button": HTMLNucleusButtonElement;
        "nucleus-tw-component": HTMLNucleusTwComponentElement;
    }
}
declare namespace LocalJSX {
    interface NucleusButton {
        "buttontype"?: 'default' | 'dark' | 'light';
    }
    interface NucleusTwComponent {
    }
    interface IntrinsicElements {
        "nucleus-button": NucleusButton;
        "nucleus-tw-component": NucleusTwComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nucleus-button": LocalJSX.NucleusButton & JSXBase.HTMLAttributes<HTMLNucleusButtonElement>;
            "nucleus-tw-component": LocalJSX.NucleusTwComponent & JSXBase.HTMLAttributes<HTMLNucleusTwComponentElement>;
        }
    }
}
